### PR TITLE
(hybris) add an empty SIGHUP signal handler to droid-hal-init in order to avoid droid-hal-init stop caused by systemd SIGHUP signals.

### PR DESCRIPTION
**Pull request by mlehtima**

### CODE REVIEW

**Comment by piggz** [comment]
Out of interest, ive no idea if its technically the right thing, but
exec nohup /usr/sbin/droid-hal-init
also works

**Comment by krnlyng** [comment]
@piggz that is really good to know

maybe we could use that instead of adding one patch to each new base...

not sure what the better method is :)

**Comment by piggz** [comment]
Im not sure if it should be
exec nohup ....
or just
nohup ... 
as nohup itself will call execvp, see https://opensource.apple.com/source/shell_cmds/shell_cmds-149/nohup/nohup.c.auto.html

**Comment by krnlyng** [comment]
no exec nohup is correct. nohup is not a builtin so it would run under different pid. with exec (builtin) it runs with the same pid

**Comment by krnlyng** [comment]
We should create a patch for the nohup thing.

**Comment by piggz** [comment]
i can create a seperate pr if you like

**Comment by sledges** [comment]
Closing as per https://github.com/mer-hybris/droid-hal-configs/pull/133

**Pull request closed without merging**
